### ISSUE TITLE
Hello,please tell me that how can I prapere the datasets "data/market1501/bounding_box_train_256_2/1373_c6s3_067817_03_00.png'"

### ISSUE THREAD

**Issue by huyanzhuolu** [CYFFF/PAAM_re-id#1]
Maybe not only the origin Market1501

**Comment by CYFFF** [comment]
They are keypoint annotations generated by CPN. Please refer to [CPN](https://github.com/chenyilun95/tf-cp). And we also upload keypoint and mask annotations to [baiduyun](https://pan.baidu.com/s/1kQzq-HDbylZxEcZRobRLDQ). The password is qp8k. Hope it helps you.

**Comment by CYFFF** [comment]
They are keypoint annotations generated by CPN. Please refer to [CPN](https://github.com/chenyilun95/tf-cpn). And we also upload keypoint and mask annotations to [Baiduyun](https://pan.baidu.com/s/1kQzq-HDbylZxEcZRobRLDQ). The password is qp8k. Hope it helps you.

**Comment by huyanzhuolu** [comment]
Thank you!
















在 2020-11-21 15:37:11，"CYF" <notifications@github.com> 写道：

They are keypoint annotations generated by CPN. Please refer to CPN. And we also upload keypoint and mask annotations to baiduyun. The password is qp8k. Hope it helps you.
